workspace: /Users/moo/workspace/

#faqs:
#  source: local
#  data:
#    questions:
#      - "A Question one?"
#      - "A Question two?"
#
#    answers:
#      - |
#          Details of the answer for question:
#          A Question one?
#      - |
#          Details of the answer for question:
#          A Question two?
#OR
#  source: url
#  data: http://domain.com/api.json

commit:
  style: CategorisedStyle # options: ImperativeMoodStyle, CategorisedStyle
  categories:
    Doc: Doc
    Bug: Bug
  words:
    - Change
    - Add
    - Create
    - Update
    - Build
    - Remove
    - Set
    - Temporarily
    - Rename
    - Implement
    - Reduce
    - Combine
    - Move
    - Configure
    - Limit
    - Exclude
    - Place
    - Use
    - Reset
    - Fix
    - Hide
    - Clean
    - Init
    - Make
    - Integrate
    - Enable
    - Disable
    - Reinstate
    - Populate
    - Replace
    - Ensure
    - Adjust
    - Override
    - Improve
    - Apply
    - Allow
    - Convert
    - Show
    - Revert
    - Extend

csfixes:
  "@PSR2": true
  "@PSR1": true
  "@Symfony": true
  "method_separation": false
  "no_unreachable_default_argument_value": false
  "combine_consecutive_unsets": false
  "no_useless_else": false
  "no_useless_return": false
  "blank_line_after_opening_tag": true
  "blank_line_before_return": true
  "cast_spaces": true
  "concat_space":
      "spacing": "one"
  "function_typehint_space": true
  "hash_to_slash_comment": true
  "lowercase_cast": true
  "magic_constant_casing": true
  "new_with_braces": true
  "no_singleline_whitespace_before_semicolons": true
  "no_unused_imports": true
  "phpdoc_align": true
  "standardize_not_equals": true
  "single_quote": true
  "pre_increment": false
  "array_syntax":
      "syntax": "short"
  "binary_operator_spaces":
      "align_double_arrow": true
      "align_equals": true
  "concat_space":
      "spacing": "one"
  "linebreak_after_opening_tag": true
  "no_trailing_comma_in_list_call": false
  "ordered_imports": true
  "phpdoc_add_missing_param_annotation": true
  "phpdoc_no_empty_return": false
  "semicolon_after_instruction": true
  "phpdoc_annotation_without_dot": true
  "phpdoc_summary": false
  "protected_to_private": false
  "phpdoc_separation": false
  "blank_line_after_opening_tag": true
  "no_extra_consecutive_blank_lines": false

