workspace: /Users/moo/workspace/
domain: "{name}.mo"


#faqs:
#  source: local
#  data:
#    questions:
#      - "A Question one?"
#      - "A Question two?"
#
#    answers:
#      - |
#          Details of the answer for question:
#          A Question one?
#      - |
#          Details of the answer for question:
#          A Question two?
#OR
#  source: url
#  data: http://domain.com/api.json

sites:
  ip: 127.0.0.1 #IP address to use for list of sites instead of finding one
commit:
  style: CategorisedStyle # options: ImperativeMoodStyle, CategorisedStyle
  categories:
    Doc: Doc
    Bug: Bug
    Test: Test
  words:
    - Invert
    - Increase
    - Refactor
    - Change
    - Add
    - Create
    - Update
    - Build
    - Remove
    - Set
    - Temporarily
    - Rename
    - Implement
    - Reduce
    - Combine
    - Move
    - Configure
    - Limit
    - Exclude
    - Place
    - Use
    - Reset
    - Fix
    - Hide
    - Clean
    - Init
    - Make
    - Integrate
    - Enable
    - Disable
    - Reinstate
    - Populate
    - Replace
    - Ensure
    - Adjust
    - Override
    - Improve
    - Apply
    - Allow
    - Convert
    - Show
    - Revert
    - Extend

csfixes:
  "@PSR2": true
  "@PSR1": true
  "@Symfony": true
  "@PhpCsFixer": true
  "mb_str_functions": false
  "array_syntax":
    "syntax": "short"
  "ordered_imports":
    "sort_algorithm": "alpha"
  "phpdoc_no_empty_return": false
  "phpdoc_to_comment": true
  "concat_space":
    "spacing": "one"
  "blank_line_before_return": true
  "hash_to_slash_comment": true
  "protected_to_private": false
  "linebreak_after_opening_tag": true
  "yoda_style": false
  "global_namespace_import":
    "import_classes": true
    "import_constants": null
    "import_functions": null
  "binary_operator_spaces":
    "default": "align"
